# Generated by Django 3.1.7 on 2021-04-30 09:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='')),
                ('title', models.CharField(max_length=50, verbose_name='Сообщение')),
                ('description', models.CharField(max_length=50, verbose_name='Краткое содержание')),
                ('content', models.TextField(verbose_name='Полное содержание')),
                ('posted', models.DateTimeField(default=datetime.datetime(2021, 4, 30, 12, 31, 16, 951330), verbose_name='Время')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('ans', models.BooleanField(verbose_name='Отправить ответ на e-mail')),
                ('email', models.CharField(max_length=50, verbose_name='E-mail')),
            ],
        ),
    ]
