# Generated by Django 3.2.2 on 2021-05-07 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0004_comment_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='description',
            field=models.CharField(max_length=150, verbose_name='Краткое содержание'),
        ),
    ]
